### ISSUE TITLE
polyfill in es modules

### ISSUE THREAD

**Issue by LarsDenBakker** [cfware/babel-plugin-bundled-import-meta#3]
I am using this plugin as part of https://github.com/open-wc/open-wc/pull/251

We want to load es modules on all browsers with support, and load a polyfill for dynamic imports.

I configured this plugin with import style `iife` which makes it work also on browsers without `import.meta.url` support, but it produces the following output:

```
const importMeta = {
  url: new URL('./demo/meta-url-test.js', typeof document !== 'undefined' ? document.currentScript && document.currentScript.src || document.baseURI : new (typeof URL !== 'undefined' ? URL : require('ur' + 'l').URL)('file:' + __filename).href).href
};
```

I think this can be simplified as just:

```
const importMeta = {
  url: new URL('./demo/meta-url-test.js', document.baseURI).href
};
```

This allows us to effectively polyfill `import.meta.url`. Do you think this is something that could be added?

**Comment by coreyfarrell** [comment]
I think it's reasonable to drop support for the node.js methods of determining the current script, if people want the node.js methods they can just leave the default `esm` import style and let rollup handle translation as part of it's own output type.

That said I think the code for `iife` will need to be:
```js
const importMeta = {
  url: new URL('./demo/meta-url-test.js', document.currentScript && document.currentScript.src || document.baseURI).href
};
```

The problem is that `document.baseURI` refers to the HTML file (a potentially incorrect fallback).  `document.currentScript.src` points to the actual script that was loaded.

I could create a new `importStyle` option `baseURI` that would use `document.baseURI` only.  Just keep in mind this would produce incorrect URL's if `http://localhost/components/index.js` was loaded by `http://localhost/index.html` so it would be important that the bundled script be written to the same path as the HTML file which loads it.  This could also be problematic for situations with SPA history API based navigation.

Let me know what you think.
https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript#Browser_compatibility

**Comment by LarsDenBakker** [comment]
Thanks for your response. Unfortunately inside a module `document.currentScript` is undefined. 

I tested a lot variations, and it seemed to work out OK. But you're right, it doesn't work out with SPA routing unless the document has a `<base href="">` specified which I think is necessary for other reasons too.

Is the URL you output in the first part (`'./demo/meta-url-test.js'` in the example) relative to the file it was bundled into, or the root of the project?

**Comment by coreyfarrell** [comment]
The idea is that `'./demo/meta-url-test.js'` is the original file that is added to the bundle.  Lets say you have sources in your project:

* ./demo/meta-url-test.png
* ./demo/meta-url-test.js - uses `import.meta.url.replace(/\.js$/, '.png')` to find `meta-url-test.png`
* ./bundle.js - just contains `import './demo/meta-url-test.js';` as the bundle entry-point source.

Lets say you have rollup output to `dist/bundle.js` (so your web server will serve `dist/`).  The expectation is that you will copy `demo/meta-url-test.png` to `dist/demo/meta-url-test.png`.
